language: generic

env:
 global:
  - GIT_REF: "NewFuture/WWOF.git"
  - GIT_AUTHOR_NAME: "NewFuture"
  - GIT_BRANCH: "gh-pages"
  - GIT_COMMITTER_NAME: "${GIT_AUTHOR_NAME}"
  - GIT_URL: "git@github.com:${GIT_REF}"
  - GIT_AUTHOR_EMAIL:  "${GIT_AUTHOR_NAME}@users.noreply.github.com"
  - GIT_COMMITTER_EMAIL: "${GIT_COMMITTER_NAME}@users.noreply.github.com"
  - EMOJI: "'eval curl -sL https://newfuture.github.io/emoji/e.sh|sh'"


# 配置git环境
before_script:
  - base64 -d <<< $ID_RSA > ~/.ssh/id_rsa 
  - chmod 600 ~/.ssh/id_rsa

# 自动update submodule
script:
  - git clone --depth=1 -b $GIT_BRANCH $GIT_URL _deploy_path 
    && cd _deploy_path
    && git submodule update --recursive --init --remote
    && git commit -am "`$EMOJI`Auto update Submodule [skip ci]"
    && git push -f "${GIT_URL}" $GIT_BRANCH:$GIT_BRANCH

branches:
  only:
    - server
    - test
    # - /^[vV](\d+\.){1,3}\d+/

git:
  depth: 1

addons:
  ssh_known_hosts:
    - github.com
